export const defaultAuthCustomization = {
  useCardCustomization: {
    cardShadowColor: "",
    cardBorderColor: "",
    cardBackgroundColor: "",
    cardShadowThickness: "md",
    cardShadow: true,
    cardBorder: true,
  },
  useInputCustomization: {
    inputLabelColor: "",
    inputLabelErrorColor: "",
    inputIconColor: "",
    inputTextColor: "",
    inputErrorTextColor: "",
    inputBorderColor: "",
    inputErrorBorderColor: "",
    inputPlaceholderTextColor: "",
    inputBorderFocusColor: "",
  },
  useCheckboxCustomization: {
    checkboxLabelColor: "",
    checkboxActiveColor: "",
    checkboxInactiveColor: "",
  },
  useButtonCustomization: {
    buttonTextColor: "",
    buttonBackgroundColor: "",
    buttonDisabledTextColor: "",
    buttonDisabledBackgroundColor: "",
  },
  useThemeCustomization: {
    headerColor: "",
    backgroundColor: "",
    linkTextColor: "",
    tertiaryTextColor: "",
    primaryCustomization: "",
    secondaryCustomization: "",
    InvalidPrimaryCustomization: "",
    InvalidSecondaryCustomization: "",
    emailVerifiedPrimaryColor: "",
    emailVerifiedSecondaryColor: "",
    emailVerifiedIconColor: "",
  },
  useNotesCustomization: {
    customNotesLogin: "",
    customNotesSignup: "",
  },
}
