export const defaultDashboardCustomization = {
  useSidebarCustomization: {
    sideBarBackgroundColor: "",
    sideBarActiveNavigationTextColor: "",
    sideBarInActiveNavigationTextColor: "",
    sideBarActiveNavigationBackgroundColor: "",
    sideBarHoverNavigationBackgroundColor: "",
    sideBarHoverNavigationTextColor: "",
    sideBarProfileBackgroundColor: "",
    sideBarProfileTextPrimaryColor: "",
    sideBarProfileTextSecondaryColor: "",
    sideBarNavigationFocusRingColor: "",
  },
  useDashboardCardCustomization: {
    dashboardCardShadowThickness: "sm",
    dashboardCardBorderColor: "",
    dashboardCardBackgroundColor: "",
    dashboardCardShadowColor: "",
    dashboardCardBorder: false,
    dashboardCardShadow: false,
  },
  useDashboardThemeCustomization: {
    mainBackgroundColor: "",
    separatorColor: "",
    dashboardHeaderNameColor: "",
    dashboardHeaderDescColor: "",
    cardHeaderPrimaryTextColor: "",
    cardHeaderSecondaryTextColor: "",
    dialogHeaderColor: "",
    cardHeaderDescriptionTextColor: "",
    missingPaypalHeaderColor: "",
    missingPaypalDescriptionColor: "",
  },
  useDashboardButtonCustomization: {
    dashboardButtonBackgroundColor: "",
    dashboardButtonTextColor: "",
    dashboardButtonDisabledBackgroundColor: "",
    dashboardButtonDisabledTextColor: "",
  },
  useTableCustomization: {
    tableHeaderTextColor: "",
    tableHoverBackgroundColor: "",
    tableIconColor: "",
    tableIconHoverColor: "",
    tableIconHoverBackgroundColor: "",
    tableRowPrimaryTextColor: "",
    tableRowSecondaryTextColor: "",
    tableRowTertiaryTextColor: "",
    tableRowBadgeOverDueTextColor: "",
    tableRowBadgeOverDueBackgroundColor: "",
    tableRowBadgePendingTextColor: "",
    tableRowBadgePendingBackgroundColor: "",
    tableRowBadgePaidTextColor: "",
    tableRowBadgePaidBackgroundColor: "",
    tableBorderColor: "",
    tableLoadingColor: "",
    tableEmptyTextColor: "",
  },
  useDialogCustomization: {
    dialogBackgroundColor: "",
    dialogCloseIconColor: "",
    dialogCloseIconBorderColor: "",
  },
  useYearSelectCustomization: {
    yearSelectBackgroundColor: "",
    yearSelectTextColor: "",
    yearSelectActiveBorderColor: "",
    yearSelectDropDownBackgroundColor: "",
    yearSelectDropDownTextColor: "",
    yearSelectDropDownActiveTextColor: "",
    yearSelectDropDownActiveBackgroundColor: "",
    yearSelectDropDownIconColor: "",
    yearSelectDropDownHoverBackgroundColor: "",
    yearSelectDropDownHoverTextColor: "",
  },
  useToastCustomization: {
    toastBackgroundColor: "",
    toastTitleColor: "",
    toastDescriptionColor: "",
    toastErrorBackgroundColor: "",
    toastErrorTitleColor: "",
    toastErrorDescriptionColor: "",
  },
  useKpiCardCustomization: {
    cardShadowColor: "",
    cardBorderColor: "",
    cardPrimaryTextColor: "",
    cardSecondaryTextColor: "",
    cardIconPrimaryColor: "",
    cardIconSecondaryColor: "",
    cardIconTertiaryColor: "",
    cardIconPrimaryBackgroundColor: "",
    cardIconSecondaryBackgroundColor: "",
    cardIconTertiaryBackgroundColor: "",
    cardShadowThickness: "sm",
    cardBackgroundColor: "",
    cardShadow: true,
    cardBorder: true,
    kpiLoadingColor: "",
  },
  useChartCustomization: {
    chartHorizontalLineColor: "",
    chartDateColor: "",
    chartPrimaryColor: "",
    chartSecondaryColor: "",
    chartTertiaryColor: "",
    chartLegendTextColor: "",
    toolTipChartDateColor: "",
    toolTipBackgroundColor: "",
    toolTipTextColor: "",
    toolTipNumberColor: "",
  },
  usePieChartColorCustomization: {
    pieColor1: "",
    pieColor2: "",
    pieColor3: "",
    pieColor4: "",
    pieColor5: "",
    pieColor6: "",
    pieColor7: "",
    pieColor8: "",
    pieFallbackColor: "",
  },
  useLogoutButtonCustomization: {
    logoutButtonBackgroundColor: "",
    logoutButtonTextColor: "",
    logoutButtonDisabledBackgroundColor: "",
    logoutButtonDisabledTextColor: "",
  },
}
