const parseDate = (str: string) => {
  const fixed = str.replace(" ", "T").replace(/(\.\d{3})\d+/, "$1") + "Z"
  return new Date(fixed)
}
export const affiliate_seed = [
  {
    id: "dd01db57-233b-4dd2-9230-d132c9462c03",
    name: "zak",
    email: "zak@gmail.com",
    type: "AFFILIATE" as const,
    createdAt: parseDate("2025-07-16 11:51:09.338106"),
    updatedAt: parseDate("2025-07-16 11:51:09.338106"),
    organizationId: "tp7JLBb5",
  },
]
export const affiliate_click_seed = [
  {
    id: "49tLBh1i",
    affiliateLinkId: "fWL6hk",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    referrer: "unknown",
    deviceType: "desktop",
    browser: "Chrome",
    os: "Windows",
    createdAt: parseDate("2025-07-16 15:29:57.940116"),
    updatedAt: parseDate("2025-07-16 15:29:57.940116"),
  },
  {
    id: "twMQa5ZP",
    affiliateLinkId: "7NyEjR",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    referrer: "unknown",
    deviceType: "desktop",
    browser: "Chrome",
    os: "Windows",
    createdAt: parseDate("2025-07-16 15:22:46.261015"),
    updatedAt: parseDate("2025-07-16 15:22:46.261015"),
  },
]
export const affiliate_invoice_seed = [
  {
    id: "pay_Gy5iQw4H8",
    paymentProvider: "stripe" as const,
    subscriptionId: "sub_1RlXCb4gdP9i8VnszkmkpkvO",
    customerId: "cus_Sgv2TtRQI8unK2",
    amount: "20.00",
    currency: "USD" as const,
    commission: "10.00",
    paidAmount: "0.00",
    affiliateLinkId: "7NyEjR",
    unpaidAmount: "10.00",
    createdAt: parseDate("2025-07-16 15:26:16.894221"),
    updatedAt: parseDate("2025-07-16 15:26:16.894221"),
  },
  {
    id: "pay_SLQGzPGq6",
    paymentProvider: "stripe" as const,
    subscriptionId: null,
    customerId: "cus_oneTime_yarRPovbr6EZKF",
    amount: "30.00",
    currency: "USD" as const,
    commission: "15.00",
    paidAmount: "0.00",
    affiliateLinkId: "7NyEjR",
    unpaidAmount: "15.00",
    createdAt: parseDate("2025-06-06 15:28:42"),
    updatedAt: parseDate("2025-07-16 15:28:42"),
  },
  {
    id: "pay_X17ybFwtv",
    paymentProvider: "stripe" as const,
    subscriptionId: "sub_1RlXCb4gdP9i8VnszkmkpkvO",
    customerId: "cus_Sgv2TtRQI8unK2",
    amount: "-20.00",
    currency: "USD" as const,
    commission: "-10.00",
    paidAmount: "0.00",
    affiliateLinkId: "7NyEjR",
    unpaidAmount: "-10.00",
    createdAt: parseDate("2025-07-16 15:26:38.589908"),
    updatedAt: parseDate("2025-07-16 15:26:38.589908"),
  },
  {
    id: "pay_iCVk6n4yP",
    paymentProvider: "stripe" as const,
    subscriptionId: "sub_1RlXCb4gdP9i8VnszkmkpkvO",
    customerId: "cus_Sgv2TtRQI8unK2",
    amount: "20.00",
    currency: "USD" as const,
    commission: "10.00",
    paidAmount: "0.00",
    affiliateLinkId: "7NyEjR",
    unpaidAmount: "10.00",
    createdAt: parseDate("2025-07-23 15:25:04"),
    updatedAt: parseDate("2025-07-16 15:25:04.430337"),
  },
  {
    id: "pay_jSLhrynfa",
    paymentProvider: "stripe" as const,
    subscriptionId: "sub_1RlXCb4gdP9i8VnszkmkpkvO",
    customerId: "cus_Sgv2TtRQI8unK2",
    amount: "-19.99",
    currency: "USD" as const,
    commission: "-10.00",
    paidAmount: "0.00",
    affiliateLinkId: "7NyEjR",
    unpaidAmount: "-9.99",
    createdAt: parseDate("2025-07-16 15:31:15.986216"),
    updatedAt: parseDate("2025-07-16 15:31:15.986216"),
  },
  {
    id: "pay_kxChw76Cv",
    paymentProvider: "stripe" as const,
    subscriptionId: "sub_1RlXCb4gdP9i8VnszkmkpkvO",
    customerId: "cus_Sgv2TtRQI8unK2",
    amount: "19.99",
    currency: "USD" as const,
    commission: "10.00",
    paidAmount: "0.00",
    affiliateLinkId: "7NyEjR",
    unpaidAmount: "9.99",
    createdAt: parseDate("2025-07-16 15:31:00.903045"),
    updatedAt: parseDate("2025-07-16 15:31:00.903045"),
  },
]
export const affiliate_link_seed = [
  {
    id: "7NyEjR",
    createdAt: parseDate("2025-07-16 11:52:26.183274"),
    updatedAt: parseDate("2025-07-16 11:52:26.183274"),
    affiliateId: "dd01db57-233b-4dd2-9230-d132c9462c03",
    organizationId: "tp7JLBb5",
  },
  {
    id: "fWL6hk",
    createdAt: parseDate("2025-07-16 14:54:05.474716"),
    updatedAt: parseDate("2025-07-16 14:54:05.474716"),
    affiliateId: "dd01db57-233b-4dd2-9230-d132c9462c03",
    organizationId: "tp7JLBb5",
  },
]
export const organization_seed = [
  {
    id: "tp7JLBb5",
    name: "Acme Inc",
    domainName: "better-auth-pi.vercel.app",
    userId: "29022934-eb52-49af-aca4-b6ed553c89dd",
    logoUrl: null,
    referralParam: "ref" as const,
    cookieLifetimeValue: 30,
    cookieLifetimeUnit: "day",
    commissionType: "percentage",
    commissionValue: "50.00",
    commissionDurationValue: 30,
    commissionDurationUnit: "day",
    currency: "USD" as const,
    createdAt: parseDate("2025-07-16 11:44:07.514288"),
    updatedAt: parseDate("2025-07-16 11:44:07.514288"),
    attributionModel: "LAST_CLICK" as const,
  },
]
export const organization_auth_customization_seed = [
  {
    id: "tp7JLBb5",
    auth: {
      useCardCustomization: {
        cardBorder: true,
        cardShadow: true,
        cardBorderColor: "",
        cardShadowColor: "",
        cardBackgroundColor: "",
        cardShadowThickness: "md",
      },
      useInputCustomization: {
        inputIconColor: "",
        inputTextColor: "",
        inputLabelColor: "",
        inputBorderColor: "",
        inputErrorTextColor: "",
        inputLabelErrorColor: "",
        inputBorderFocusColor: "",
        inputErrorBorderColor: "",
        inputPlaceholderTextColor: "",
      },
      useNotesCustomization: {
        customNotesLogin:
          '<p style="text-align: center;"><span style="color: rgb(13, 227, 17);">This is The Login Page</span></p><p style="text-align: center;"><span style="color: rgb(13, 227, 17);">falkfjalkfjlakjflajf</span></p>',
        customNotesSignup:
          '<p style="text-align: center;"><span style="color: rgb(61, 22, 202);">This is the Signup Page</span></p><p style="text-align: center;"><span style="color: rgb(61, 22, 202);">flakjflakjflajdfalkfja</span></p><p style="text-align: center;"><span style="color: rgb(61, 22, 202);">falkjfalfjalf</span></p>',
      },
      useThemeCustomization: {
        headerColor: "",
        linkTextColor: "",
        backgroundColor: "#7dc04b",
        tertiaryTextColor: "",
        primaryCustomization: "",
        emailVerifiedIconColor: "",
        secondaryCustomization: "",
        emailVerifiedPrimaryColor: "",
        InvalidPrimaryCustomization: "",
        emailVerifiedSecondaryColor: "",
        InvalidSecondaryCustomization: "",
      },
      useButtonCustomization: {
        buttonTextColor: "",
        buttonBackgroundColor: "",
        buttonDisabledTextColor: "",
        buttonDisabledBackgroundColor: "",
      },
      useCheckboxCustomization: {
        checkboxLabelColor: "",
        checkboxActiveColor: "",
        checkboxInactiveColor: "",
      },
    },
    createdAt: parseDate("2025-08-12 10:53:45.821"),
    updatedAt: parseDate("2025-08-12 22:15:36.47"),
  },
]
export const organization_dashboard_customization_seed = [
  {
    id: "tp7JLBb5",
    dashboard: {
      useChartCustomization: {
        chartDateColor: "",
        chartFourthColor: "",
        toolTipTextColor: "",
        chartPrimaryColor: "",
        chartTertiaryColor: "",
        toolTipNumberColor: "",
        chartSecondaryColor: "",
        chartLegendTextColor: "",
        toolTipChartDateColor: "",
        toolTipBackgroundColor: "",
        chartHorizontalLineColor: "",
      },
      useTableCustomization: {
        tableIconColor: "",
        tableBorderColor: "",
        tableIconHoverColor: "",
        tableHeaderTextColor: "",
        tableRowPrimaryTextColor: "",
        tableHoverBackgroundColor: "",
        tableRowTertiaryTextColor: "",
        tableRowBadgePaidTextColor: "",
        tableRowSecondaryTextColor: "",
        tableIconHoverBackgroundColor: "",
        tableRowBadgeOverDueTextColor: "",
        tableRowBadgePendingTextColor: "",
        tableRowBadgePaidBackgroundColor: "",
        tableRowBadgeOverDueBackgroundColor: "",
        tableRowBadgePendingBackgroundColor: "",
      },
      useToastCustomization: {
        toastTitleColor: "",
        toastBackgroundColor: "",
        toastErrorTitleColor: "",
        toastDescriptionColor: "",
        toastErrorBackgroundColor: "",
        toastErrorDescriptionColor: "",
      },
      useDialogCustomization: {
        dialogCloseIconColor: "",
        dialogBackgroundColor: "",
        dialogCloseIconBorderColor: "",
      },
      useKpiCardCustomization: {
        cardBorder: true,
        cardShadow: true,
        cardBorderColor: "",
        cardShadowColor: "",
        cardBackgroundColor: "",
        cardShadowThickness: "sm",
        cardIconPrimaryColor: "",
        cardPrimaryTextColor: "",
        cardIconTertiaryColor: "",
        cardIconSecondaryColor: "",
        cardSecondaryTextColor: "",
        cardIconPrimaryBackgroundColor: "",
        cardIconTertiaryBackgroundColor: "",
        cardIconSecondaryBackgroundColor: "",
      },
      useSidebarCustomization: {
        sideBarBackgroundColor: "#256490",
        sideBarProfileBackgroundColor: "",
        sideBarProfileTextPrimaryColor: "",
        sideBarHoverNavigationTextColor: "",
        sideBarNavigationFocusRingColor: "",
        sideBarActiveNavigationTextColor: "",
        sideBarProfileTextSecondaryColor: "",
        sideBarInActiveNavigationTextColor: "",
        sideBarHoverNavigationBackgroundColor: "",
        sideBarActiveNavigationBackgroundColor: "",
      },
      useYearSelectCustomization: {
        yearSelectTextColor: "",
        yearSelectBackgroundColor: "",
        yearSelectActiveBorderColor: "",
        yearSelectDropDownIconColor: "",
        yearSelectDropDownTextColor: "",
        yearSelectDropDownHoverTextColor: "",
        yearSelectDropDownActiveTextColor: "",
        yearSelectDropDownBackgroundColor: "",
        yearSelectDropDownHoverBackgroundColor: "",
        yearSelectDropDownActiveBackgroundColor: "",
      },
      useDashboardCardCustomization: {
        dashboardCardBorder: false,
        dashboardCardShadow: false,
        dashboardCardBorderColor: "",
        dashboardCardShadowColor: "",
        dashboardCardBackgroundColor: "",
        dashboardCardShadowThickness: "sm",
      },
      usePieChartColorCustomization: {
        pieColor1: "",
        pieColor2: "",
        pieColor3: "",
        pieColor4: "",
        pieColor5: "",
        pieColor6: "",
        pieColor7: "",
        pieColor8: "",
        pieFallbackColor: "",
      },
      useDashboardThemeCustomization: {
        separatorColor: "",
        dialogHeaderColor: "",
        mainBackgroundColor: "#a9f584",
        dashboardHeaderDescColor: "",
        dashboardHeaderNameColor: "",
        cardHeaderPrimaryTextColor: "#98caa8",
        cardHeaderSecondaryTextColor: "",
        cardHeaderDescriptionTextColor: "",
      },
      useDashboardButtonCustomization: {
        dashboardButtonTextColor: "",
        dashboardButtonBackgroundColor: "",
        dashboardButtonDisabledTextColor: "",
        dashboardButtonDisabledBackgroundColor: "",
      },
    },
    createdAt: parseDate("2025-08-12 10:53:45.24"),
    updatedAt: parseDate("2025-08-12 20:11:21.372"),
  },
]
export const user_seed = [
  {
    id: "29022934-eb52-49af-aca4-b6ed553c89dd",
    name: "zak",
    email: "zak@gmail.com",
    role: "OWNER" as const,
    type: "SELLER" as const,
    createdAt: parseDate("2025-07-16 11:43:21.288497"),
    updatedAt: parseDate("2025-07-16 11:43:21.288497"),
  },
]
export const account_seed = [
  {
    id: "f1a2b3c4-d5e6-7f89-0123-456789abcdef", // constant UUID
    userId: "29022934-eb52-49af-aca4-b6ed553c89dd",
    provider: "credentials" as const,
    providerAccountId: "zak@gmail.com",
    password: "$2b$10$StHXjJi6UvIye0GVPmDp4uRXnjAuBAuqNZhnzTLb24U0.l98LjH3C",
    emailVerified: parseDate("2025-07-16 11:43:21.288497"),
    createdAt: parseDate("2025-07-16 11:43:21.288497"),
    updatedAt: parseDate("2025-07-16 11:43:21.288497"),
  },
]

export const affiliate_account_seed = [
  {
    id: "a1b2c3d4-e5f6-7890-1234-56789abcdef0", // constant UUID
    affiliateId: "dd01db57-233b-4dd2-9230-d132c9462c03",
    provider: "credentials" as const,
    providerAccountId: "zak@gmail.com",
    password: "$2b$10$PnbuKyGgf4XRYCHUr.EDtu6yTaVgGdihZM/u5q54Jryix9xYRG0q2",
    emailVerified: parseDate("2025-07-16 11:51:09.338106"),
    createdAt: parseDate("2025-07-16 11:51:09.338106"),
    updatedAt: parseDate("2025-07-16 11:51:09.338106"),
  },
]
