export type AuthCustomizationSettings = {
  backgroundColor: string;
  showShadow: boolean;
  shadowColor: string;
  shadowThickness: "sm" | "md" | "lg" | "xl";
  borderColor: string;
  showBorder: boolean;
  includeOrgName: boolean;
  logoUrl: string;
  cardBackgroundColor: string;
  primaryTextColor: string;
  linkTextColor: string;
  secondaryTextColor: string;
  errorColor: string;
  inputBorderColor: string;
  inputBorderErrorColor: string;
  inputBorderFocusColor: string;
  inputTextColor: string;
  placeholderTextColor: string;
  iconColor: string;
  toastBackgroundColor: string;
  toastTextColor: string;
  toastErrorBackgroundColor: string;
  toastErrorTextColor: string;
  buttonBackgroundColor: string;
  buttonTextColor: string;
  buttonDisabledBackgroundColor: string;
  buttonDisabledTextColor: string;
  checkboxActiveColor: string;
  checkboxInactiveColor: string;
  customNotes: string;
};
